name: portfolio_tracker_app
description: "A sample holdings tracker app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  app_bar_with_search_switch: ^1.8.6
  decimal: ^3.0.0
  dio: ^5.7.0
  equatable: ^2.0.7
  fl_chart: ^0.69.2
  flash: 3.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  meta: ^1.15.0
  rational: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  lint: 2.3.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - .env
